FROM python:3.6

WORKDIR /usr/src/app
COPY ./requirements.txt /usr/src/app/requirements.txt

RUN pip install \
    --no-cache-dir \
    -r requirements.txt

COPY . /usr/src/app

CMD ["python3", "src/main.py"]