version: '2'

services:

  app:
    ports:
      - '5000:5000'
    build:
      context: ./frontend/app
      dockerfile: Dockerfile
    volumes:
      - ./frontend/app:/usr/src/app'


  api:
    environment:
      DEBUG: 'yes'

    ports:
      - '3000:3000'
    build: 
      context: ./backend/api
      dockerfile: Dockerfile
    environment:
      - FLASK_ENV=development
      - DATASTORE_URI=postgres://postgres@datastore
    restart: always