version: '2'

services:

  app:
    ports:
      - '5000:5000'
    volumes:
      - ./frontend/app:/usr/src/app'

  web:
    ports:
      - '8080:80'

  api:
    environment:
      DEBUG: 'yes'

    ports:
      - '3000:3000'
