version: '2'

services:

  app:
    build: 
      context: ./frontend/app
      dockerfile: Dockerfile-prod

    environment:
      NODE_ENV: development

    expose:
      - 80

  api:
    build: 
      context: ./backend/api
      dockerfile: Dockerfile-prod
    environment:
      - FLASK_ENV=development
      - DATASTORE_URI=postgres://postgres@datastore
    expose:
      - 5000
    restart: always

  datastore:
    build: './backend/datastore'

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    depends_on:
      - api
      - app